# Generated by Django 4.0.3 on 2022-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userorders',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
