# Generated by Django 4.0.3 on 2022-04-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_userprofile_alter_order_ordernumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='cartOf',
        ),
    ]
