# Generated by Django 4.0.3 on 2022-04-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_cartof_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='cartOf',
        ),
    ]
